spring:
  application:
    name: Backend
  profiles:
    active: ${ENV:dev}
  mail:
   host: smtp.gmail.com
   port: 587
   username: vishwanathkhuli347@gmail.com
   password: hwht ncrz kvpo fmmk
   properties:
    mail:
     smtp:
      auth: true
      starttls:
       enable: true
   default-encoding: UTF-8
  security:
   oauth2: 
    client:
     registration: 
      google:
       client-id: ${GOOGLE_CLIENT_ID}
       client-secret: ${GOOGLE_CLIENT_SECRET}
       redirect-uri: ${GOOGLE_REDIRECT_URI}
       scope:
        - email
        - profile
     provider:
      google:
        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
        token-uri: https://oauth2.googleapis.com/token
        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  

server:
  port: 8080

# Strong 256-bit JWT secret (must be at least 32 characters for HS256)
jwt:
  secret: "ThisIsAReallyStrongHS256SecretKey@123"  # 32+ characters, strong & random
  token:
    validity: 259200000   # 3 days in milliseconds
  refresh:
    token:
      validity: 604800000  # 7 days in millisecond

