spring:
  application:
    name: Backend
  profiles.active: ${ENV:dev}

server:
  port: 8080

jwt.secret : vishwanathkkhuli19012001mangalwadramapurhaliyalbengaluruasdfasdfasdfasdfsdfasdfasd
jwt.token.validity : 604800000  # 7 days in milliseconds
jwt.refresh.token.validity : 604800000  # 7 days in milliseconds
